update action to findout bug of README.md not push right

diff --git a/.github/workflows/waka-readme.yml b/.github/workflows/waka-readme.yml
--- a/.github/workflows/waka-readme.yml
+++ b/.github/workflows/waka-readme.yml
@@ -20,33 +20,33 @@ jobs:
         uses: athul/waka-readme@v0.1.5
         with:
           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
-      - name: Push new README.md
-        run: |
-         echo "GITHUB_ACTOR -> ${GITHUB_ACTOR}"
-         echo "GITHUB_REPOSITORY -> ${GITHUB_REPOSITORY}"
-         COMMIT_MSG="update README.md data of waka, by github action at cron set"
-         if [ -z "${COMMIT_MSG}" ]; then
-          echo "error: not found env: COMMIT_MSG"
-          exit 1
-         fi
-         echo "COMMIT_MSG -> ${COMMIT_MSG}"
-         # https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
-         remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
-         git config http.sslVerify false
-         git config user.name "${GITHUB_ACTOR}"
-         git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
-         git remote add publisher "${remote_repo}"
+      # - name: Push new README.md
+      #   run: |
+      #    echo "GITHUB_ACTOR -> ${GITHUB_ACTOR}"
+      #    echo "GITHUB_REPOSITORY -> ${GITHUB_REPOSITORY}"
+      #    COMMIT_MSG="update README.md data of waka, by github action at cron set"
+      #    if [ -z "${COMMIT_MSG}" ]; then
+      #     echo "error: not found env: COMMIT_MSG"
+      #     exit 1
+      #    fi
+      #    echo "COMMIT_MSG -> ${COMMIT_MSG}"
+      #    # https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
+      #    remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
+      #    git config http.sslVerify false
+      #    git config user.name "${GITHUB_ACTOR}"
+      #    git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
+      #    git remote add publisher "${remote_repo}"
 
-         # useful for debugging
-         git show-ref
-         git branch --verbose
+      #    # useful for debugging
+      #    git show-ref
+      #    git branch --verbose
 
-         # install lfs hooks
-         git lfs install
+      #    # install lfs hooks
+      #    git lfs install
 
-         # publish any new files
-         git checkout main
-         git add -A
-         git commit -m "${COMMIT_MSG}" || exit 0
-         git pull --rebase publisher main
-         git push publisher main
+      #    # publish any new files
+      #    git checkout main
+      #    git add -A
+      #    git commit -m "${COMMIT_MSG}" || exit 0
+      #    git pull --rebase publisher main
+      #    git push publisher main
